### ISSUE TITLE
Remove slots option

### ISSUE THREAD

**Issue by Shresht7** [Shresht7/markdown-slots#1]
Add option to remove slots upon replacement

e.g.

```yaml
- name: markdown-slots
  uses: Shresht7/markdown-slots
  with:
    slots:
      test: Slot Text
```

turns

```md
<!-- slot: test -->
<!-- /slot -->
```

into

```md
Slot Text
```
